---

- name: Creating vHost file
  template:
    src: reverse-proxy.conf.j2
    dest: "{{ nginx.config_volume }}/{{ fullinstancename }}.conf"
    mode: '0644'
  notify:
      - reload_nginx_service


  