---
# tasks file for deploy-odoo
- import_tasks: 0-register-platform-defaults.yml
  tags: deployodoo, stopinstance, restartinstance, suspendinstance, startinstance

- import_tasks: deploy-odoo.yml
  tags: deployodoo

- import_tasks: add-vhost.yml
  tags: deployodoo

- import_tasks: stop-instance.yml
  tags: stopinstance, restartinstance, suspendinstance

- import_tasks: start-instance.yml
  tags: startinstance, restartinstance