---
- name: Creating Docker compose file if it does not exist
  template:
    src: docker-compose.yml.j2
    force: no
    dest: "{{ xayma_odoo_paths.instance }}/docker-compose.yml"
    mode: '0644'

- name: Creating Odoo config file  if it does not exist
  template:
    force: no
    src: odoo.conf.j2
    dest: "{{ xayma_odoo_paths.config }}/odoo.conf"
    mode: '0644'

- name: Deleting comments in the configuration file
  lineinfile:
    path: "{{ xayma_odoo_paths.config }}/odoo.conf"
    state: absent
    regexp: "^[ #\\r\\n]"

- name: Starting Odoo instance
  docker_compose:
    project_src: "{{ xayma_odoo_paths.instance }}"
    state: present
  when: instancename != xayma_odoo.instancename # We make sure the user has provided an instance name


#- name: Updating the Nginx vHost file
#  template:
#    src: reverse-proxy.conf.j2
#    dest: "{{ nginx_config_volume_path }}/{{ fullinstancename }}.conf"
#    mode: '0644'
#  notify:
#      - reload_nginx_service