---

- name: Starting Odoo instance
  docker_compose:
    project_src: "{{ xayma_odoo_paths.instance }}"
    state: present
  when: instancename != xayma_odoo.instancename # We make sure the user has provided an instance name
      