---

organization: "{{ xayma_odoo.organization }}"
instancename: "{{ xayma_odoo.instancename }}"
version: "{{ xayma_odoo.version }}"
domain: "{{ instancename }}"
_name: "{{ xayma_odoo.name }}"
fullinstancename: "{{organization}}_{{instancename}}_odoo{{version|default(xayma_odoo.version)|int}}"
fullinstancename_db: "{{organization}}_{{instancename}}_postgres"
defaultdomain: "{{platform_domain}}"

domains:
    - "{{ domain }}"
    - "www.{{ domain }}"
    - "{{instancename}}.{{ defaultdomain }}"

xayma_odoo_paths:
    instance: "{{services_path}}/{{organization}}/{{instancename}}_odoo{{version|int}}"
    config: "{{services_path}}/{{organization}}/{{instancename}}_odoo{{version|int}}/config/"
    logs: "{{services_path}}/{{organization}}/{{instancename}}_odoo{{version|int}}/logs/"

    
# TODO
# Create a variable name 'instanceame_with_id'